Form/AdminFilterFormType.php
<?php

/*
 * This file is part of the LyraAdminBundle package.
 *
 * Copyright 2011 Massimo Giagnoni <gimassimo@gmail.com>
 *
 * This source file is subject to the MIT license. Full copyright and license
 * information are in the LICENSE file distributed with this source code.
 */

namespace Lyra\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Lyra\AdminBundle\Util\Util;

class AdminFilterFormType extends AbstractType
{
    protected $name;

    protected $fields;

    public function __construct($name, $fields)
    {
        $this->name = $name;
        $this->fields = $fields;
    }

    public function buildForm(FormBuilder $builder, array $options)
    {
        foreach ($this->fields as $field => $attrs) {
            $builder->add($field, $attrs['widget'], $attrs['options']);
        }
    }

    public function getName()
    {
        return 'lyra_admin_form_filter_'.$this->name;
    }
}

Form/AdminFormType.php
<?php

/*
 * This file is part of the LyraAdminBundle package.
 *
 * Copyright 2011 Massimo Giagnoni <gimassimo@gmail.com>
 *
 * This source file is subject to the MIT license. Full copyright and license
 * information are in the LICENSE file distributed with this source code.
 */

namespace Lyra\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Lyra\AdminBundle\Util\Util;

/**
 * Generic form type for all admin forms.
 */
class AdminFormType extends AbstractType
{
    protected $name;

    protected $fields;

    public function __construct($name, $fields)
    {
        $this->name = $name;
        $this->fields = $fields;
    }

    public function buildForm(FormBuilder $builder, array $options)
    {
        foreach ($this->fields as $field => $attrs) {
            $builder->add($attrs['tag'], $attrs['widget'], $attrs['options']);
        }
    }

    public function getName()
    {
        return 'lyra_admin_form_'.$this->name;
    }
}

Form/DatePickerType.php
<?php

 /*
  * This file is part of the LyraAdminBundle package.
  *
  * Copyright 2011 Massimo Giagnoni <gimassimo@gmail.com>
  *
  * This source file is subject to the MIT license. Full copyright and license
  * information are in the LICENSE file distributed with this source code.
  */

namespace Lyra\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer;
use Symfony\Component\Form\ReversedTransformer;
use Lyra\AdminBundle\Util\Util;

class DatePickerType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $format = $options['format'];
        $pattern = null;

        $allowedFormatOptionValues = array(
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::LONG,
            \IntlDateFormatter::MEDIUM,
            \IntlDateFormatter::SHORT,
        );

        // If $format is not in the allowed options, it's considered as the pattern of the formatter if it is a string
        if (!in_array($format, $allowedFormatOptionValues, true)) {
            if (is_string($format)) {
                $defaultOptions = $this->getDefaultOptions($options);

                $format = $defaultOptions['format'];
                $pattern = $options['format'];
            } else {
                throw new CreationException('The "format" option must be one of the IntlDateFormatter constants (FULL, LONG, MEDIUM, SHORT) or a string representing a custom pattern');
            }
        }

        $formatter = new \IntlDateFormatter(
            \Locale::getDefault(),
            $format,
            \IntlDateFormatter::NONE,
            \DateTimeZone::UTC,
            \IntlDateFormatter::GREGORIAN,
            $pattern
        );

        $builder->appendClientTransformer(new DateTimeToLocalizedStringTransformer($options['data_timezone'], $options['user_timezone'], $format, \IntlDateFormatter::NONE, \IntlDateFormatter::GREGORIAN, $pattern));

        if ($options['input'] === 'string') {
            $builder->appendNormTransformer(new ReversedTransformer(
                new DateTimeToStringTransformer($options['data_timezone'], $options['data_timezone'], 'Y-m-d')
            ));
        } elseif ($options['input'] === 'timestamp') {
            $builder->appendNormTransformer(new ReversedTransformer(
                new DateTimeToTimestampTransformer($options['data_timezone'], $options['data_timezone'])
            ));
        } elseif ($options['input'] === 'array') {
            $builder->appendNormTransformer(new ReversedTransformer(
                new DateTimeToArrayTransformer($options['data_timezone'], $options['data_timezone'], array('year', 'month', 'day'))
            ));
        }

        $builder
            ->setAttribute('date_pattern', $formatter->getPattern());
    }

    public function buildViewBottomUp(FormView $view, FormInterface $form)
    {
        $view->setAttribute('data-date', Util::ICUTojQueryDate($form->getAttribute('date_pattern')));
    }

    public function getDefaultOptions(array $options)
    {
        return array(
            'input'          => 'datetime',
            'format'         => \IntlDateFormatter::MEDIUM,
            'data_timezone'  => null,
            'user_timezone'  => null,
            // Don't modify \DateTime classes by reference, we treat
            // them like immutable value objects
            'by_reference'   => false,
            'error_bubbling' => false,
        );
    }

    public function getAllowedOptionValues(array $options)
    {
        return array(
            'input'       => array(
                'datetime',
                'string',
                'timestamp',
                'array',
            ),
        );
    }

    public function getName()
    {
        return 'date_picker';
    }

    public function getParent(array $options)
    {
        return 'field';
    }
}

Form/DateRangeType.php
<?php

/*
 * This file is part of the LyraAdminBundle package.
 *
 * Copyright 2011 Massimo Giagnoni <gimassimo@gmail.com>
 *
 * This source file is subject to the MIT license. Full copyright and license
 * information are in the LICENSE file distributed with this source code.
 */

namespace Lyra\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class DateRangeType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $options['child_options'] = array_merge($options['child_options'], array('required' => false));
        $builder
            ->add('from', $options['child_widget'], $options['child_options'])
            ->add('to', $options['child_widget'], $options['child_options']);
    }

    public function getName()
    {
        return 'daterange';
    }

    public function getDefaultOptions(array $options)
    {
        return array(
            'child_widget' => 'datetime',
            'child_options' => array()
        );
    }
}

Form/DateTimePickerType.php
<?php

 /*
  * This file is part of the LyraAdminBundle package.
  *
  * Copyright 2011 Massimo Giagnoni <gimassimo@gmail.com>
  *
  * This source file is subject to the MIT license. Full copyright and license
  * information are in the LICENSE file distributed with this source code.
  */

namespace Lyra\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\Exception\CreationException;
use Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToLocalizedStringTransformer;
use Symfony\Component\Form\ReversedTransformer;
use Lyra\AdminBundle\Util\Util;

class DateTimePickerType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $dateFormat = $options['date_format'];
        $timeFormat = $options['time_format'];
        $pattern = null;

        $allowedFormatOptionValues = array(
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::LONG,
            \IntlDateFormatter::MEDIUM,
            \IntlDateFormatter::SHORT,
        );

        // If $format is not in the allowed options, it's considered as the pattern of the formatter if it is a string
        $defaultOptions = $this->getDefaultOptions($options);

        if (!in_array($dateFormat, $allowedFormatOptionValues, true)) {
            if (is_string($dateFormat)) {
                $dateFormat = $defaultOptions['date_format'];
                $pattern = $options['date_format'];
            } else {
                throw new CreationException('The "date_format" option must be one of the IntlDateFormatter constants (FULL, LONG, MEDIUM, SHORT) or a string representing a custom pattern');
            }
        }

        $formatter = new \IntlDateFormatter(
            \Locale::getDefault(),
            $dateFormat,
            \IntlDateFormatter::NONE,
            \DateTimeZone::UTC,
            \IntlDateFormatter::GREGORIAN,
            $pattern
        );

        $datePattern = $formatter->getPattern();

        if (!in_array($timeFormat, $allowedFormatOptionValues, true)) {
            if (is_string($timeFormat)) {
                $timeFormat = $defaultOptions['time_format'];
                $pattern = $options['time_format'];
            } else {
                throw new CreationException('The "time_format" option must be one of the IntlDateFormatter constants (FULL, LONG, MEDIUM, SHORT) or a string representing a custom pattern');
            }
        }

        $formatter = new \IntlDateFormatter(
            \Locale::getDefault(),
            \IntlDateFormatter::NONE,
            $timeFormat,
            \DateTimeZone::UTC,
            \IntlDateFormatter::GREGORIAN,
            $pattern
        );

        $timePattern = $formatter->getPattern();

        if (null !== $pattern) {
            $pattern = $datePattern . ' ' . $timePattern;
        }

        $builder->appendClientTransformer(new DateTimeToLocalizedStringTransformer($options['data_timezone'], $options['user_timezone'], $dateFormat, $timeFormat, \IntlDateFormatter::GREGORIAN, $pattern));


        if ($options['input'] === 'string') {
            $builder->appendNormTransformer(new ReversedTransformer(
                new DateTimeToStringTransformer($options['data_timezone'], $options['data_timezone'], 'Y-m-d')
            ));
        } elseif ($options['input'] === 'timestamp') {
            $builder->appendNormTransformer(new ReversedTransformer(
                new DateTimeToTimestampTransformer($options['data_timezone'], $options['data_timezone'])
            ));
        } elseif ($options['input'] === 'array') {
            $builder->appendNormTransformer(new ReversedTransformer(
                new DateTimeToArrayTransformer($options['data_timezone'], $options['data_timezone'], array('year', 'month', 'day'))
            ));
        }

        $builder
            ->setAttribute('date_pattern', $datePattern)
            ->setAttribute('time_pattern', $timePattern);
    }

    public function buildViewBottomUp(FormView $view, FormInterface $form)
    {
        $view->setAttribute('data-date', Util::ICUTojQueryDate($form->getAttribute('date_pattern')));
        $timePattern = $form->getAttribute('time_pattern');
        $view->setAttribute('data-time', Util::ICUTojQueryDate($timePattern));
        $view->setAttribute('data-ampm', false !== strpos($timePattern, 'h') ? '1' : '0');

    }

    public function getDefaultOptions(array $options)
    {
        return array(
            'input'         => 'datetime',
            'data_timezone' => null,
            'user_timezone' => null,
            'date_format'   => \IntlDateFormatter::MEDIUM,
            'time_format'   => \IntlDateFormatter::SHORT,
            // Don't modify \DateTime classes by reference, we treat
            // them like immutable value objects
            'by_reference'  => false,
        );
    }

    public function getAllowedOptionValues(array $options)
    {
        return array(
            'input'       => array(
                'datetime',
                'string',
                'timestamp',
                'array',
            ),
        );
    }

    public function getName()
    {
        return 'datetime_picker';
    }

    public function getParent(array $options)
    {
        return 'field';
    }
}

Form/FormInterface.php
<?php

/*
 * This file is part of the LyraAdminBundle package.
 *
 * Copyright 2011-2012 Massimo Giagnoni <gimassimo@gmail.com>
 *
 * This source file is subject to the MIT license. Full copyright and license
 * information are in the LICENSE file distributed with this source code.
 */

namespace Lyra\AdminBundle\Form;

use Lyra\AdminBundle\Action\ActionCollectionInterface;

interface FormInterface
{
    /**
     * Sets the model name.
     *
     * @param string $modelName
     */
    function setModelName($modelName);

    /**
     * Gets the model name.
     *
     * @return string
     */
    function getModelName();

    /**
     * Sets form actions.
     *
     * These are the actions executed when the form is submitted (new, edit).
     *
     * @param \Lyra\AdminBundle\Action\ActionCollectionInterface $actions
     */
    function setActions(ActionCollectionInterface $actions);

    /**
     * Gets form actions.
     *
     * @return \Lyra\AdminBundle\Action\ActionCollectionInterface
     */
    function getActions();

    /**
     * Sets new form actions.
     *
     * These are the actions users execute through buttons
     * at the top of a new form (default:index, save).
     *
     * @param \Lyra\AdminBundle\Action\ActionCollectionInterface $actions
     */
    function setNewActions(ActionCollectionInterface $actions);

    /**
     * Gets new form actions.
     *
     * @return \Lyra\AdminBundle\Action\ActionCollectionInterface
     */
    function getNewActions();

    /**
     * Sets edit form actions.
     *
     * These are the actions users execute through buttons
     * at the top of an edit form (default:index, save, delete).
     *
     * @param \Lyra\AdminBundle\Action\ActionCollectionInterface $actions
     */
    function setEditActions(ActionCollectionInterface $actions);

    /**
     * Gets edit form actions.
     *
     * @return \Lyra\AdminBundle\Action\ActionCollectionInterface
     */
    function getEditActions();

    /**
     * Sets form action.
     *
     * This is the action executed when the form is submitted.
     *
     * @param string $actionName (new/edit)
     * @throws InvalidArgumentException if action named $actionName does not exist in form config
     */
    function setAction($actionName);

    /**
     * Gets form action.
     *
     * Action is set by name and retrieved as object.
     *
     * @return \Lyra\AdminBundle\Action\ActionInterface
     */
    function getAction();

    /**
     * Sets form template.
     *
     * @param string $template
     */
    function setTemplate($template);

    /**
     * Gets form template.
     *
     * @return string
     */
    function getTemplate();

    /**
     * Sets the form translation domain.
     *
     * Used in templates to translate form title, labels.
     *
     * @param string $transDomain
     */
    function setTransDomain($transDomain);

    /**
     * Gets the form translation domain.
     *
     * @return string
     */
    function getTransDomain();

    /**
     * Sets form type class.
     *
     * @param string $class FQN of type class
     */
    function setClass($class);

    /**
     * Gets form type class.
     *
     * @return string
     */
    function getClass();

    /**
     * Sets form data class.
     *
     * @param string $dataClass FQN of data class
     */
    function setDataClass($dataClass);

    /**
     * Gets form data class.
     *
     * @return string
     */
    function getDataClass();

    /**
     * Sets the data/object associated to the form.
     *
     * @param mixed $data
     */
    function setData($data);

    /**
     * Gets the data/object associated to the form.
     *
     * @return mixed
     */
    function getData();

    /**
     * Gets the form object.
     *
     * @param array $data data passed to the form
     *
     * @return \Symfony\Component\Form\Form
     */
    function create();

    /**
     * Gets the form view object.
     *
     * @param string $field
     *
     * @return \Symfony\Component\Form\FormView
     */
    function getView($field);

    /**
     * Sets fields groups (fieldsets).
     *
     * @param array $groups
     */
    function setGroups(array $groups);

    /**
     * Gets fields groups (fieldsets).
     *
     * @return array
     */
    function getGroups();

    /**
     * Sets the form title (new,edit).
     *
     * @param string $newTitle
     * @param string $editTitle
     */
    function setTitle($newTitle, $editTitle);

    /**
     * Gets form title (header).
     *
     * @return string edit or new title based on form action
     */
    function getTitle();

    /**
     * Sets fields configuration options.
     *
     * @param array $fields
     */
    function setFields($fields);

    /**
     * Gets fields configuration options.
     *
     * @return array
     */
    function getFields();

    /**
     * Checks if form contains a given widget.
     *
     * @param string $widget widget name
     */
    function hasWidget($widget);
}

Resources/views/Form/action.html.twig
{% set params = object is defined and action.hasIdParam ? { 'id' : object.id } : {} %}
{% set class = 'button action-'~action~(action.buttonIcon ? ' ui-icon-'~action.buttonIcon : '')~(action.hasDialog ? ' dialog' : '')~(action.buttonStyle is defined ? ' '~action.buttonStyle  : '') %}
{% set text = (action.text|default(form.modelName~'.form.action.'~action))|trans({}, action.trans_domain|default(form.transDomain)) %}
{% if action.routeName is empty %}
    <button class="{{ class }}">{{ text }}</button>
{% else %}
    <a href="{{ path(action.routeName, params) }}" class="{{ class }}">{{ text }}</a>
{% endif %}

Resources/views/Form/fields.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block date_picker_widget %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' date-picker'}) %}
    {{ block('field_widget') }}
{% endblock %}
{% block datetime_picker_widget %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' datetime-picker'}) %}
    {{ block('field_widget') }}
{% endblock %}
{% block daterange_widget %}
{% spaceless %}
    <div class="daterange-container">
        <div class="daterange-from">
            {{ form_errors(form.from) }}
            {{ form_label(form.from) }}
            {{ form_widget(form.from) }}
        </div>
        <div class="daterange-to">
            {{ form_errors(form.to) }}
            {{ form_label(form.to) }}
            {{ form_widget(form.to) }}
        </div>
    </div>
{% endspaceless %}
{% endblock %}

Resources/views/Form/form.html.twig
{% extends 'LyraAdminBundle::layout.html.twig' %}
{% form_theme form.view 'LyraAdminBundle:Form:form_theme.html.twig' %}
{% block title %}
    {{ form.title|trans({}, form.transDomain) }}
{% endblock %}
{% block content %}
<div id="ly-form-wrapper">
    {% block form_title %}
        <h1>{{ block('title') }}</h1>
    {% endblock %}
    {% block form_actions %}
    <div class="form-actions">
        {% for action in (form.action.name == 'new' ? form.newActions : form.editActions) %}
            {% include action.template|default('LyraAdminBundle:Form:action.html.twig') %}
        {% endfor %}    </div>
    {% endblock %}
    {% block form %}
        {{ form_errors(form.view) }}
        {% set params = object.id is defined ? { 'id' : object.id } : {} %}
        <form class="ly-form" action="{{ path(form.action.routeName, params) }}" method="post">
            <div id="column-1">
            {% for group in form.groups %}
                {% block form_group %}
                <fieldset>
                {% if group.caption %}
                    <legend>{{ group.caption|trans({}, form.transDomain) }}</legend>
                {% endif %}
                <ol>
                {% for field in group.fields %}
                    {% set fld = not group.embed is defined ? form.fields[field] : '' %}
                    {% set name = fld is empty ? field : fld.tag %}
                    {% set view = form.view(group.embed|default(null)) %}
                    {% block form_field %}
                    <li>
                    {{ form_errors(view[name]) }}
                    {% if not (fld.label is defined and fld.label is empty) %}
                        {{ form_label(view[name], fld.label is defined ? fld.label : null) }}
                    {% endif %}
                    {{ form_widget(view[name]) }}
                    </li>
                    {% endblock form_field %}
                {% endfor %}
                </ol>
                </fieldset>
                {% endblock form_group %}
                {% if group.break_after %}
                    </div>
                    <div id="column-2">
                {% endif %}
            {% endfor %}
            </div>
            {{ form_row(form.view._token) }}
            <hr class="clear" />
            <input class="button" type="submit" value="{{ 'form.button.submit'|trans({}, 'LyraAdminBundle') }}" />
        </form>
    {% endblock %}
</div>
{% endblock %}
{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" type="text/css" href="{{ asset('bundles/lyraadmin/css/form.css') }}" />
{% if form.hasWidget('datetime_picker') %}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/lyraadmin/css/jquery-ui-timepicker-addon.css') }}" />
{% endif %}
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script type="text/javascript" src="{{ asset('bundles/lyraadmin/js/lyra_dual_list.js') }}"></script>
<script type="text/javascript" src="{{ asset('bundles/lyraadmin/js/lyra_confirm.js') }}"></script>
<script type="text/javascript" src="{{ asset('bundles/lyraadmin/js/form.js') }}"></script>
{% include 'LyraAdminBundle:Admin:datepicker_js.html.twig' with { 'renderer' : form } %}
{% endblock %}

Resources/views/Form/form_theme.html.twig
{% extends 'form_div_layout.html.twig' %}

{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
    <ul class="error-list">
        {% for error in errors %}
            <li>{{
                error.messagePluralization is null
                    ? error.messageTemplate|trans(error.messageParameters, 'validators')
                    : error.messageTemplate|transchoice(error.messagePluralization, error.messageParameters, 'validators')
            }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}
{% block datetime_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {{ block('field_widget') }}
    {% else %}
            {{ form_errors(form.date) }}
            {{ form_errors(form.time) }}
            {{ form_widget(form.date) }}
            {{ form_widget(form.time) }}
    {% endif %}
{% endspaceless %}
{% endblock datetime_widget %}

{% block date_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {{ block('field_widget') }}
    {% else %}
            {{ date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw }}
    {% endif %}
{% endspaceless %}
{% endblock date_widget %}

{% block time_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {{ block('field_widget') }}
    {% else %}
            {{ form_widget(form.hour, { 'attr': { 'size': '1' } }) }}:{{ form_widget(form.minute, { 'attr': { 'size': '1' } }) }}{% if with_seconds %}:{{ form_widget(form.second, { 'attr': { 'size': '1' } }) }}{% endif %}
    {% endif %}
{% endspaceless %}
{% endblock time_widget %}

{% block choice_widget %}
{% spaceless %}
    {% if expanded %}
        {% set attr = attr|merge( { 'class' : 'choices-list' }) %}
        <div {{ block('widget_container_attributes') }}>
        {% for child in form %}
            {{ form_widget(child) }}
            {{ form_label(child) }}
        {% endfor %}
        </div>
    {% else %}
    <select {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>
        {% if empty_value is not none %}
            <option value="">{{ empty_value|trans }}</option>
        {% endif %}
        {% if preferred_choices|length > 0 %}
            {% set options = preferred_choices %}
            {{ block('widget_choice_options') }}
            {% if choices|length > 0 and separator is not none %}
                <option disabled="disabled">{{ separator }}</option>
            {% endif %}
        {% endif %}
        {% set options = choices %}
        {{ block('widget_choice_options') }}
    </select>
    {% endif %}
{% endspaceless %}
{% endblock choice_widget %}